browser: chrome
os: Windows
osVersion: 11
browserVersion: latest
resolution: 1920x1080
consoleLogs: info
networkLogs: true
video: true
screenshot: true
selfHeal: true
smartWait: true
debug: true
interactiveDebugging: true
local: false