browser: chrome
os: Windows
osVersion: 11
browserVersion: latest
resolution: 1920x1080
buildName: Playwright Desktop Build
consoleLogs: info
networkLogs: true
video: true
screenshot: true
selfHealing: true
smartWait: true
debug: true
interactiveDebugging: true
local: false
projectName: Valentino Beans
sessionName: Checkout Flow - Desktop