{
 "title": "Harvest of Quality",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Infrastructure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "__auto" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" },
    { "expr": "nodejs_gc_duration_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Environment & Context",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "playwright_test_environment", "legendFormat": "__auto" },
    { "expr": "playwright_test_group_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Test Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "playwright_test_total", "legendFormat": "__auto" },
    { "expr": "playwright_test_failures_total", "legendFormat": "__auto" },
    { "expr": "playwright_test_retry_total", "legendFormat": "__auto" },
    { "expr": "playwright_test_group_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Test Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "playwright_test_duration_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "playwright_test_avg_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}